Feat/spacing tokens implementation
Decathlon/vitamin-design pull request #98
Opened 2022-10-11 07:59 UTC by SimonLeclercq

Basic set for design tokens `spacings`, with their description

2022-10-11 13:07 UTC, lauthieb requested changes

2022-10-11 13:14 UTC, SimonLeclercq commented on design-tokens/Base.json
> +    }
Figma-tokens limitation, not able to modify it

2022-10-11 13:50 UTC, lauthieb requested changes

2022-10-11 13:50 UTC, lauthieb commented on design-tokens/Base.json
> +    }
@SimonLeclercq Even if you do it as code?
Btw, I thought it was possible to drag and drop elements inside the plugin in order to modify the order.

2022-10-17 06:45 UTC, thibault-mahe approved these changes

2022-10-19 20:04 UTC, lauthieb approved these changes

2022-11-10 16:51 UTC, merged